package com.cokiri.coinkiri.util

const val LOGIN = "LOGIN"
const val ANALYSIS = "ANALYSIS"
const val POST = "POST"
const val HOME = "HOME"
const val PRICE = "PRICE"
const val PROFILE = "PROFILE"


const val FOLLOW = "FOLLOW"

const val COMMUNITY_DETAIL_SCREEN = "COMMUNITY_DETAIL_SCREEN"

const val COIN_DETAIL_SCREEN = "COIN_DETAIL_SCREEN"

const val ANALYSIS_WRITE_SCREEN = "ANALYSIS_WRITE_SCREEN"

const val CREATE_POST_SCREEN_FOR_COMMUNITY = "CREATE_POST_SCREEN_FOR_COMMUNITY"
const val CREATE_POST_SCREEN_FOR_ANALYSIS = "CREATE_POST_SCREEN_FOR_ANALYSIS"